baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3

[params]
  disqusShortname = "your disqus id." # optional
  toc = true # optional, When set to TRUE this parameter, table of contents appears in all articles.
